version: "3.8"

services:

  pokeapi:
    container_name: pokeapi
    image: myimage
    build:
        context: .
        dockerfile: ./Dockerfile
    command: ["uvicorn", "pokeapi.main:app", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "8000:80"
    stdin_open: true
    tty: true



